version: '3.8'

networks:
  codetruck_network:
    name: codetruck_network
    #external: true

services:
  pg-database:
    container_name: pg-database
    image: postgres:15.6
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
    networks:
      - codetruck_network
    restart: always

  db-minio:
    container_name: db-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - codetruck_network
    volumes:
      - './minio-data:/data'
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
      - MINIO_DEFAULT_BUCKETS=image-autoparts
    command: server /data --console-address ":9001"
    restart: always
    